# BEFORE YOU GET STARTED
Make sure you use the requirements.txt file to create an environment with the appropriate packages.

The purpose of this notebook is to do some basic analysis on the data. More detailed analysis is available in the notebooks for each country.

Also, make sure you have [Mito](https://www.trymito.io/) installed!

In [1]:
import pandas as pd

In [2]:
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

In [3]:
uk_df = pd.read_csv("social_media-GB-monthly-201305-202305.csv")

In [4]:
jp_df = pd.read_csv("social_media-JP-monthly-201305-202305.csv")

In [5]:
us_df = pd.read_csv("social_media-US-monthly-201305-202305.csv")

In [6]:
sk_df = pd.read_csv("social_media-KR-monthly-201305-202305.csv")

In [7]:
uk_df.head()

,Date,Facebook,Twitter,Pinterest,Tumblr,Instagram,reddit,StumbleUpon,YouTube,LinkedIn,Google+,VKontakte,news.ycombinator.com,Fark,Digg,Other
0,2013-05,61.95,19.34,3.69,0.0,0.0,4.53,6.93,2.75,0.34,0.24,0.03,0.0,0.02,0.02,0.16
1,2013-06,62.61,19.93,3.73,0.0,0.0,4.06,6.25,2.46,0.36,0.24,0.03,0.0,0.04,0.03,0.27
2,2013-07,58.82,22.21,4.10,0.0,0.0,4.13,6.92,2.71,0.46,0.30,0.01,0.0,0.03,0.05,0.27
3,2013-08,54.96,23.91,4.69,0.0,0.0,4.49,7.85,3.02,0.53,0.32,0.02,0.0,0.03,0.07,0.13
4,2013-09,52.65,24.90,5.15,0.0,0.0,5.69,7.78,2.86,0.46,0.32,0.01,0.0,0.02,0.04,0.12

In [8]:
uk_df.describe()

,Facebook,Twitter,Pinterest,Tumblr,Instagram,reddit,StumbleUpon,YouTube,LinkedIn,Google+,VKontakte,news.ycombinator.com,Fark,Digg,Other
count,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000
mean,64.339174,15.897355,7.671818,2.559752,4.274959,1.802231,1.042231,1.737273,0.462149,0.087438,0.046198,0.039256,0.010331,0.008099,0.021818
std,12.173516,7.169432,4.162081,3.521994,5.445515,1.064863,1.796676,1.242002,0.374433,0.091965,0.031152,0.033346,0.009481,0.014219,0.044197
min,36.010000,4.530000,3.150000,0.000000,0.000000,0.350000,0.000000,0.020000,0.040000,0.000000,0.010000,0.000000,0.000000,0.000000,0.000000
25%,56.050000,10.820000,4.690000,0.830000,0.000000,0.970000,0.000000,0.310000,0.190000,0.000000,0.030000,0.020000,0.000000,0.000000,0.000000
50%,61.370000,14.410000,6.020000,1.700000,2.030000,1.580000,0.450000,1.940000,0.380000,0.060000,0.040000,0.030000,0.010000,0.000000,0.010000
75%,76.070000,20.250000,9.920000,2.740000,6.680000,2.250000,0.990000,2.520000,0.640000,0.170000,0.060000,0.050000,0.010000,0.010000,0.020000
max,87.080000,37.140000,23.200000,17.820000,18.530000,5.690000,7.850000,4.980000,1.970000,0.320000,0.230000,0.180000,0.050000,0.070000,0.270000

In [9]:
# important to convert it to datetime!
uk_df['Date'] = pd.to_datetime(uk_df['Date'])

In [10]:
p = figure(width=600, height=600, title="UK Data Test",  x_axis_type = 'datetime', x_axis_label = 'Date', y_axis_label= 'Percent')
p.line(y=uk_df['Facebook'], x=uk_df['Date'], line_width=2, color='red', legend_label='Facebook')
p.line(y=uk_df['Twitter'], x=uk_df['Date'], line_width=2, color='green', legend_label='Twitter')
show(p)